variables:
  - name: artifactPipelineId
    value: 3
    readonly: true

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none

  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: Install Node

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project: fd8c7c84-cd77-4296-b4ef-bbfbf354ee1b
      pipeline: ${{variables.artifactPipelineId}}
      buildVersionToDownload: latestFromBranch
      branchName: refs/heads/master
      downloadType: specific
      downloadPath: $(System.ArtifactsDirectory)
    displayName: Download build output

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: $(System.ArtifactsDirectory)/output/*.zip
      destinationFolder: $(System.ArtifactsDirectory)/extracted
      cleanDestinationFolder: true
    displayName: Extract build output

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: $(System.ArtifactsDirectory)/extracted/*.tgz
      destinationFolder: $(System.ArtifactsDirectory)/unpacked
      cleanDestinationFolder: true
    displayName: Unpack build output

  - script: |
      cd $(System.ArtifactsDirectory)/unpacked/package
      echo Package contents:
      dir
      echo Packge details:
      cat package.json
    displayName: Print package info

  - task: Npm@1
    inputs:
      command: publish
      workingDir: $(System.ArtifactsDirectory)/unpacked/package
      publishEndpoint: npm
    displayName: Publish to npm
